# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates. 

namespace: app
name: app

# By default `component` will be equal to `{{ .Values.name }}`
#component: my-component

# By default `partOf` will be equal to `{{ .Values.namespace }}`
#partOf: my-system

# By default `containerName` will be equal to `{{ .Values.namespace }}-{{.Values.name }}`
containerName:

ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 80

image:
  repository: "nginx"
  tag: latest
  pullPolicy: IfNotPresent
  # Flux Image policy & repository  
  update: 
    enabled: true
    # Image repository
    # https://fluxcd.io/docs/components/image/imagerepositories/
    interval: 1m0s
    # Image policy
    # https://fluxcd.io/docs/components/image/imagepolicies/
    filterTags:
      # ${PREFIX}-${GIT_SHA:0:7}-$(date +%s)
      pattern: '^dev-[a-fA-F0-9]+-(?P<ts>.*)'
      extract: '$ts'
    policy:
      numerical:
        order: asc

resources:
  requests:
    memory: "128Mi"
    cpu: "0.25"
  limits:
    memory: "256Mi"
    cpu: "0.5"

replicaCount: 1

ingress:
#  host: your.hostname.io
#  http:
#    - path: /app/*
#      pathType: prefix
#      port:  80

healthEndpoint: /health
healthPort: 80

readyEndpoint: /health
readyPort: 80
