name: psql-db-tool
namespace: edig-psql-db-tool
linkerdEnable: enabled
healthEndpoint: /is_alive
healthPort: 8080
readyEndpoint: /is_alive
readyPort: 8080

ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
image:
  repository: tpdbtpregistry7x1zzt.azurecr.io/eviny-digital-oss-net-core/psql-db-tool
  tag: latest
  update:
    enabled: false
ingress:
  enabled: false
aadpodidentity:
  enabled: true
  selector: oss-net-core-inventory-identity
  akvcsidriver:
    enabled: true
    provider: azure
    usePodIdentity: true
    keyvaultName: my-cool-key-vault-name
    cloudName: AzurePublicCloud
    tenantId: 12f1bdca-9eec-45f6-a63e-2061b957e8ee
    secretObjects:
      - secretName: secret-oss-db-password
        objectName: secret-oss-db-password
        key: secret-oss-db-password
        type: Opaque
        data:
          - objectName: secret-oss-db-password
            objectType: secret
            key: secret-oss-db-password
      - secretName: azure-storage-secret # ks8 secret name
        type: Opaque
        data:
          - objectName: azurestorageaccountkey
            objectType: secret
            key: azurestorageaccountkey
          - objectName: azurestorageaccountname
            objectType: secret
            key: azurestorageaccountname

envVars:
  - name: azure-storage-secret
    valueFrom:
      secretKeyRef:
        name: azure-storage-secret
        key: azure-storage-secret
  - name: PG-PASSWORD
    valueFrom:
      secretKeyRef:
        name: secret-oss-db-password
        key: secret-oss-db-password
