{{- if and (.Values.aadpodidentity.enabled) (not .Values.aadpodidentity.selector) }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: "{{ .Values.name }}-identity"
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.aadpodidentity }}
  type: {{ .type }}
  resourceID: {{ .resourceID | quote }}
  clientID: {{ .clientID | quote }}
  {{- end }}
{{- end }}