{{- if and (.Values.aadpodidentity.enabled) (not .Values.aadpodidentity.selector) }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: "{{ .Values.name }}-binding"
  namespace: {{ .Values.namespace }}
spec:
  azureIdentity: "{{ .Values.name }}-identity"
  selector: "{{ .Values.name }}-identity"
{{- end }}