apiVersion: apps/v1
kind: Deployment

#imagePullPolicy: {{ .Values.image.pullPolicy }}

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Values.component | default .Values.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.partOf | default .Values.namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ default (printf "%s-%s" .Values.namespace .Values.name) .Values.containerName | quote }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
        {{- with .Values.resources }}
        resources:
          {{- with .requests }}
          requests:
            memory: {{ .memory | quote }}
            cpu: {{ .cpu | quote }}
          {{- end }}
          {{- with .limits }}
          limits:
            memory: {{ .memory | quote }}
            cpu: {{ .cpu | quote }}
          {{- end }}
        {{- end }}

        {{- if .Values.ports }}
        ports:
        {{- range .Values.ports }}
        - protocol: {{ .protocol | upper }}
          containerPort: {{ .targetPort }}
        {{- end }}
        {{- end }}

        {{- if .Values.envVars }}
        env:
          {{- range .Values.envVars }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
        {{- end }}

        livenessProbe:
          httpGet:
            path: {{ .Values.healthEndpoint | quote }}
            port: {{ .Values.healthPort }}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: {{ .Values.readyEndpoint | quote }}
            port: {{ .Values.readyPort }}
          initialDelaySeconds: 5
          periodSeconds: 10