{{- if .Values.image.update.enabled }}
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  image: {{ .Values.image.repository | quote }}
  interval: {{ .Values.image.update.interval | default "1m0s" }}
{{- end }}