{{- if .Values.aadpodidentity.akvcsidriver.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.name }}-akvcsistore"
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.aadpodidentity.akvcsidriver.provider | quote }}
  secretObjects:
    {{- range .Values.aadpodidentity.akvcsidriver.secretObjects }}                             
    - secretName: {{ .secretName | quote }}
      type: {{ .type | quote }}
      data:
      {{- range .data }}                             
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
          {{- end }}
    {{- end }}
  parameters:
    usePodIdentity: {{ .Values.aadpodidentity.akvcsidriver.usePodIdentity | quote }}     
    keyvaultName: {{ .Values.aadpodidentity.akvcsidriver.keyvaultName | quote }} 
    cloudName: {{ .Values.aadpodidentity.akvcsidriver.cloudName | quote }}
    tenantId: {{ .Values.aadpodidentity.akvcsidriver.tenantId | quote  }}
    objects: |
      array:
            {{- range .Values.aadpodidentity.akvcsidriver.secretObjects }}
            {{- range .data }}
        - | 
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
            {{- end }}
            {{- end }}

{{- end }}