{{- if .Values.aadpodidentity.akvcsidriver.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.name }}-akvcsistore"
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.aadpodidentity.akvcsidriver.provider | quote }}
  secretObjects:
    {{- range .Values.aadpodidentity.akvcsidriver.secretObjects }}                             
    - secretName: {{ (lower .secretName) | quote }}
      type: {{ .type | quote }}
      data:
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
    {{- end }}
  parameters:
    usePodIdentity: {{ .Values.aadpodidentity.akvcsidriver.usePodIdentity | quote }}     
    keyvaultName: {{ .Values.aadpodidentity.akvcsidriver.keyvaultName | quote }} 
    cloudName: {{ .Values.aadpodidentity.akvcsidriver.cloudName | quote }}
    tenantId: {{ .Values.aadpodidentity.akvcsidriver.tenantId | quote  }}
    objects: 
    {{- range .Values.aadpodidentity.akvcsidriver.secretObjects }}
      - objectName: {{ .objectName }}
        objectType: {{ .objectType }}
    {{- end }}
{{- end }}
