apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
{{- if .Values.ports }}
  ports:
{{- range .Values.ports }}
    - protocol: {{ .protocol | upper }}
      port: {{ .servicePort }}
      targetPort: {{ .name }}
{{- end }}
{{- end }}